### ISSUE TITLE
微信支付android版报错

### ISSUE THREAD

**Issue by ganglee** [glustful/ionicPayDemo#10]
您好，首先表示感谢 🙏； 我直接运行demo，支付宝没问题；
但是微信支付在android和ios上都不行，
安卓报错：sendPayReq:服务器请求错误；
ios报错：sendPayReq：支付失败；
不知道是否有时间可以看下，先谢谢了

**Comment by glustful** [comment]
这个demo是不能直接运行，我在写的时候是根据别人反馈的问题与提供的支付宝信息与微信信息调试的信息，因此支付宝能成功，微信的签名与数据接口已经不能使用了，你先按照readme文件配置成你真实的信息再测试。

**Comment by ganglee** [comment]
好，怪不得，谢谢，我的微信支付正在审核，审核通过了我就试试 🙏
